# Generated by Django 5.0.3 on 2024-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mashxur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/mashxur')),
                ('chegirma', models.CharField(max_length=30)),
            ],
        ),
    ]
