# Generated by Django 5.0.3 on 2024-03-24 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_mashxur'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('NO', 'Noactive')], default='NO', max_length=2),
        ),
    ]
